### ISSUE TITLE
mb video guide? and can i use it to host game server?

### ISSUE THREAD

**Issue by BagroSlave** [june07/ngrok-dns#2]
mb video guide? and can i use it to host game server?

**Comment by ko4ergin** [comment]
nope

**Comment by june07** [comment]
Made an important update to use the official @ngrok/ngrok package. Works on my end now, the backend was fine. See the example and give it another go... ymmv

**Comment by june07** [comment]
There is still this issue https://github.com/orgs/community/discussions/45635, where 307 redirects are not followed. I'm not sure how applicable that will be in hosting your @SirScarlet game server?!
